---
title: Articles
timezone: America/Toronto
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
permalink: "/:title/"
url: http://articles.jeffjewiss.com
kramdown:
  input: GFM
gems:
- jekyll-sitemap
sass:
  sass_dir: _sass
  style: :compressed
exclude:
- README.md
- ".editorconfig"
- ".gitignore"
- Procfile
