markdown: kramdown
highlighter: pygments
permalink: /:title
url: "http://articles.jeffjewiss.com"
timezone: America/Toronto

kramdown:
  input: GFM

# Use the following plug-ins
gems:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed

# Exclude these files from your production _site
exclude:
  - README.md
